--DDL  CRIACAO DA TABELA 
USE DESAFIO;
GO

--DDL CRIANDO TABELAS COM CHAVE PRIMÁRIA E ESTRANGEIRA

CREATE TABLE CIDADE
(
  ID_CIDADE int identity(1,1) NOT NULL PRIMARY KEY,
  NOME_CIDADE VARCHAR(60) NOT NULL,
  UF VARCHAR(2) NOT NULL
);

CREATE TABLE CLIENTE
(
  ID_CLIENTE int identity(1,1) NOT NULL PRIMARY KEY,
  NOME_CLIENTE VARCHAR(60) NOT NULL,
  ENDEREÇO VARCHAR(60) NOT NULL,
  NUMERO VARCHAR(10),
  CEP VARCHAR(9)NOT NULL,
  ID_CIDADE int NOT NULL,
  FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
 );

CREATE TABLE VENDEDORES
(
  ID_VENDEDOR int identity(1,1) NOT NULL PRIMARY KEY,
  NOME_VENDEDORES VARCHAR(60) NOT NULL,
  SALARIO DECIMAL(10,2)
); 

CREATE TABLE VENDAS
(
  NUM_VENDA int identity(1,1) NOT NULL PRIMARY KEY,
  DATA_VENDA DATETIME NOT NULL,
  ID_CLIENTE INT NOT NULL,
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  ID_VENDEDOR INT NOT NULL,
  FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR),
  STATUS CHAR(1)
 );

 CREATE TABLE CATEGORIA
(
  ID_CATEGORIA int identity(1,1) NOT NULL PRIMARY KEY,
  NOME_CATEGORIA VARCHAR(20) NOT NULL  
); 

CREATE TABLE UNIDADE
(
  ID_UNIDADE VARCHAR(3) NOT NULL PRIMARY KEY,
  DESC_UNIDADE VARCHAR(25) 
); 

CREATE TABLE PRODUTOS
(
  ID_PRODUTO int identity(1,1) NOT NULL PRIMARY KEY,
  NOME_PRODUTO VARCHAR(50) NOT NULL,
  ID_CATEGORIA INT NOT NULL,
  FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
  ID_UNIDADE VARCHAR(3) NOT NULL,
  FOREIGN KEY(ID_UNIDADE) REFERENCES UNIDADE(ID_UNIDADE),
  PRECO DECIMAL(10,2)
 );

 CREATE TABLE VENDA_ITENS
(
  NUM_VENDA int identity(1,1) NOT NULL PRIMARY KEY,
  FOREIGN KEY(NUM_VENDA) REFERENCES VENDAS(NUM_VENDA),
  NUM_SE int NOT NULL,
  ID_PRODUTO INT NOT NULL,
  FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
  QTDE DECIMAL(10,2),
  VAL_UNITARIO DECIMAL(10,2),
  VAL_TOTAL DECIMAL(10,2) NULL
 );




